# GitHub Sponsors configuration
# If you'd like to support this project, you can enable GitHub Sponsors

# github: Luccifer
# patreon: # your_patreon_username
# ko_fi: # your_ko_fi_username
# custom: # your_custom_donation_url

