name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    
    - name: Install dependencies
      run: npm install
    
    - name: Build extension
      run: npm run build
    
    - name: Create ZIP
      run: npm run build:zip
    
    - name: Get version from package.json
      id: package-version
      run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*.zip
        name: Release v${{ steps.package-version.outputs.VERSION }}
        body: |
          ## IBM Cognos TM1 Web Clipboard Extension v${{ steps.package-version.outputs.VERSION }}
          
          ### Installation
          1. Download the ZIP file below
          2. Extract to a folder
          3. Load unpacked extension in Chrome/Edge
          
          ### Requirements
          - Chrome 96+ or Edge 96+
          - HTTPS connection to TM1 Web
          
          See [README.md](https://github.com/Luccifer/IBM-Cognos-TM1-Web-Clipboard-Extension#readme) for full documentation.
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

